language: c
addons:
  apt_packages:
    - libgmp-dev

os:
  - linux
env:
  - TEST_SUITE=gap
  - TEST_SUITE=hpcgap
compiler:
  - gcc
  - clang

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./run_tests.sh $TEST_SUITE
