name: IO
version: 4.6.0
date: 2019-03-18
description: |
    Bindings for low level C library I/O routines

authors:
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.10"

www: https://gap-packages.github.io/io
readme: README.md
packageinfo: https://gap-packages.github.io/io/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/io/releases/download/v4.6.0/io-4.6.0.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/io/releases/download/v4.6.0/io-4.6.0.tar.bz2

abstract: |
    The <span class="pkgname">IO</span> package, as its name suggests,    provides bindings for <span class="pkgname">GAP</span> to the lower    levels of Input/Output functionality in the C library.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
